root_desc: Open de Ala Delta de Pedro Bernardo
description: Página del Open de Ala Delta de Pedro Bernardo (Ávila)
server: true
auto: true
destination: _site/open
url: http://localhost/open
exclude: bin, fs_templates, tmp
paginate: 4
